export const APP_PREFIX_PATH = '';
// export const API_URL = 'https://meditrekaccess.com/meditrek/server/adminAPI/';
//export const API_URL = "http://localhost:3001/meditrek/server/adminAPI/";
// export const API_URL = "https://meditrek.votivereact.in/meditrek/server/adminAPI/";
// export const API_URL = "https://api.meditrekaccess.com/app/meditrek/server/adminAPI/";
export const API_URL = "http://localhost:3009/meditrek/server/adminAPI/";
//export const IMAGE_PATH = 'https://meditrekaccess.com/meditrek/server/uploads/'
export const IMAGE_PATH = 'https://meditrek.votivereact.in/uploads/'
// export const IMAGE_PATH = 'https://api.meditrekaccess.com/app/meditrek/server/uploads/'